import Error404_img from "src/assets/error/404.svg"
import logoDark from "src/assets/static/Logo-Dark.svg"
import logoLight from "src/assets/static/Logo-Light.svg"
import bg_header from "src/assets/static/Background.png"
import imgBerger_menu from "src/assets/static/icon-hamburger.svg"
import Website_Mockup from "src/assets/static/Website Mockup.png"
import Feature from "src/assets/static/Feature.png"
import heart from "src/assets/static/Heart.svg"
import Avatar1 from "src/assets/static/User Avatar 1.png"
import Avatar2 from "src/assets/static/User Avatar 2.png"
import Avatar3 from "src/assets/static/User Avatar 3.png"
import Dashboard_desktop from "src/assets/static/Dashboard-Desktop.png"
import Dashboard_mobile from "src/assets/static/Dashboard-Mobile.png"
import Dashboard_tablet from "src/assets/static/Dashboard-Tablet.png"
import Pattern from "src/assets/static/Pattern.png"
import Checkmark from "src/assets/static/Checkmark.svg"
import CheckmarkGray from "src/assets/static/Checkmark gray.svg"
import NotAvailable from "src/assets/static/Not Available.svg"
import NotAvailableGray from "src/assets/static/Not Available gray.svg"
import minus from "src/assets/static/Minus.svg"
import plus from "src/assets/static/Plus.svg"
import Dribble from "src/assets/static/Dribbble.svg"
import Blogger from "src/assets/static/Blogger.svg"
import Discord from "src/assets/static/Discord.svg"
import Youtube from "src/assets/static/Youtube.svg"
import LinkedIn from "src/assets/static/LinkedIn.svg"
import Twitter from "src/assets/static/Twitter.svg"
import VideoCover from "src/assets/static/Video-dashboard.png"
import Analytics1 from "src/assets/static/Analytics Overview.png"
import Analytics2 from "src/assets/static/Page Views Overview.png"
import TopLinksClicked from "src/assets/static/Top Links Clicked.png"
import Countries from "src/assets/static/Countries.png"

export {Error404_img, logoDark, logoLight, bg_header, imgBerger_menu, Website_Mockup, Feature, heart, Avatar1, Avatar2, Avatar3, Dashboard_desktop , Dashboard_mobile, Dashboard_tablet, Pattern, Checkmark, CheckmarkGray, NotAvailable, NotAvailableGray, plus, minus, Dribble, Blogger, Discord, LinkedIn, Twitter , Youtube,
    VideoCover, Analytics1, Analytics2, Countries, TopLinksClicked
}